language: python
dist: trusty
python:
  - "3.6"
install:
    # using tensorflow-gpu on travis does not work
  - pip3 install tensorflow
  - pip3 install nose2
  - pip3 install flake8
  - pip3 install scipy
  - pip3 install -e git+https://github.com/facebookresearch/fastText#egg=version_pkg
  - pip3 install gensim
script: 
  - ./scripts/run_tests.sh
  - flake8 .
